 
version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    dns:
      - 8.8.8.8      # Google DNS
      - 8.8.4.4      # Backup DNS


networks:
  app-network:
    driver: bridge
