name: CD
permissions:
   contents: read
   id-token: write
   packages: write
   actions: read
   checks: write
   deployments: write
   pull-requests: write
   statuses: write
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 
          password: 
      - name: Build Docker images
        run: |
          docker build -t NEHA/chat-app-frontend ./frontend
          docker build -t NEHA/chat-app-backend ./backend

      - name: Push Docker images
        run: |
          docker push NEHA/chat-app-frontend
          docker push NEHA/chat-app-backend

      - name: Install Render CLI
        run: |
          curl --request GET \
          --url 'https://api.render.com/v1/services?limit=20' \
          --header 'Accept: application/json' \
          --header 'Authorization: Bearer {{SECRETS.RENDER_TOKEN}}'

      - name: Deploy to Render
        run: |
          render deploy service-id=tea-d3ha4logjchc73abknmg
