name: CD
permissions:
   contents: read
   id-token: write
   packages: write
   actions: read
   checks: write
   deployments: write
   pull-requests: write
   statuses: write
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nehaatwork0 
          password: docker005
      - name: Build Docker images
        run: |
          docker build -t nehaatwork0/chat-app-frontend ./frontend
          docker build -t nehaatwork0/chat-app-backend ./backend

      - name: Push Docker images
        run: |
          docker push nehaatwork0/chat-app-frontend
          docker push nehaatwork0/chat-app-backend

      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: rnd_kSxqGH5WYz3s8biqKC1O2vZVljrd
          RENDER_SERVICE_ID: srv-d3hka1r3fgac739sdg2g
        run: |
          echo "Triggering Render deploy..."
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -d '{}'
