name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: EHA
          password: docker2005

      - name: Build and Push Docker Images
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

      - name: Deploy to Production
        run: |
          ssh user@your-server-ip 'docker compose -f /path/to/docker-compose.yml pull && docker compose -f /path/to/docker-compose.yml up -d'
